channel_id_name_mapping={
    "1"  : "Amazon_USA",
    "12" : "Amazon_India",
    "14" : "Flipkart",
    "15" : "Bonanza",
    "3"  : "eBay",
    "24" : "Etsy"
}

channel_id_currency_mapping={
    "1"  : "$",
    "12" : "₹",
    "14" : "₹",
    "15" : "£",
    "3"  : "$"
}

cat_subcat = {
    "Etsy":{
        "Accessories":[
            "Baby Accessories",
            "Belts and Braces",
            "Bouquets and Corsages",
            "Costume Accessories",
            "Gloves and Mittens",
            "Hair Accessories",
            "Hand Fans",
            "Hats and Caps",
            "Keychains and Lanyards",
            "Patches and Pins",
            "Scarves and Wraps",
            "Suit and Tie Accessories",
            "Sunglasses and Eyewear",
            "Umbrellas and Rain Accessories"
        ],
        "Art and Collectibles":[
            "Artist Trading Cards",
            "Collectibles",
            "Dolls and Miniatures",
            "Drawing and Illustration",
            "Fibre Arts",
            "Fine Art Ceramics",
            "Glass Art",
            "Mixed Media and Collage",
            "Painting",
            "Photography",
            "Prints",
            "Sculpture"
        ],
        "Bags and Purses":[
            "Accessory Cases",
            "Backpacks",
            "Clothing and Shoe Bags",
            "Cosmetic and Toiletry Storage",
            "Diaper Bags",
            "Electronics Cases",
            "Food and Insulated Bags",
            "Handbags",
            "Hip Bags",
            "Keychains and Lanyards",
            "Luggage and Travel",
            "Market Bags",
            "Messenger Bags",
            "Pouches and Coin Purses",
            "Sports Bags",
            "Totes",
            "Wallets and Money Clips"
        ],
        "Bath and Beauty":[
            "Baby and Child Care",
            "Bath Accessories",
            "Cosmetic and Toiletry Storage",
            "Essential Oils",
            "Fragrances",
            "Hair Care",
            "Makeup and Cosmetics",
            "Personal Care",
            "Skin Care",
            "Soaps",
            "Spa and Relaxation"
        ],
        "Books  Films and Music":[
            "Books",
            "Movies",
            "Music",
            "Video Cases and Tins"
        ],
        "Clothing":[
            "Boys Clothing",
            "Girls Clothing",
            "Mens Clothing",
            "Unisex Kids Clothing",
            "Womens Clothing"
        ],
        "Craft Supplies and Tools":[
            "Home and Hobby",
            "Jewellery and Beauty",
            "Paper  Party and Kids",
            "Sculpting and Forming",
            "Sewing and Fiber",
            "Visual Arts"
        ],
        "Electronics and Accessories":[
            "Audio",
            "Batteries and Charging",
            "Cables and Cords",
            "Cameras",
            "Car Parts and Accessories",
            "Cell Phone Accessories",
            "Computers and Peripherals",
            "Decals and Skins",
            "DIY Kits",
            "Docking and Stands",
            "Electronics Cases",
            "Gadgets",
            "Maker Supplies",
            "Parts and Electrical",
            "Telephones and Handsets",
            "TV and Projection",
            "Video Games"
        ],
        "Home and Living":[
            "Bathroom",
            "Bedding",
            "Cleaning Supplies",
            "Curtains and Window Treatments",
            "Floor and Rugs",
            "Food and Drink",
            "Furniture",
            "Home Appliances",
            "Home Decor",
            "Home Improvement",
            "Kitchen and Dining",
            "Lighting",
            "Office",
            "Outdoor and Gardening",
            "Spirituality and Religion",
            "Storage and Organisation"
        ],
        "Jewellery":[
            "Body Jewellery",
            "Bracelets",
            "Brooches  Pins and Clips",
            "Cremation and Memorial Jewellery",
            "Cuff Links and Tie Clips",
            "Earrings",
            "Jewellery Sets",
            "Jewellery Storage",
            "Necklaces",
            "Rings",
            "Watches",
            "Wearable Tech Jewellery"
        ],
        "Paper and Party Supplies":[
            "Paper",
            "Party Supplies"
        ],
        "Pet Supplies":[
            "Beekeeping",
            "Horse Riding and Farm Animals",
            "Pet Bedding",
            "Pet Carriers and Houses",
            "Pet Clothing  Accessories and Shoes",
            "Pet Collars and Leashes",
            "Pet Feeding",
            "Pet Furniture",
            "Pet Gates and Fences",
            "Pet Health and Wellness",
            "Pet Storage",
            "Urns and Memorials"
        ],
        "Shoes":[
            "Boys Shoes",
            "Girls Shoes",
            "Insoles and Accessories",
            "Mens Shoes",
            "Womens Shoes"
        ],
        "Toys and Games":[
            "Games and Puzzles",
            "Sports and Outdoor Recreation",
            "Toys"
        ],
        "Weddings":[
            "Accessories",
            "Clothing",
            "Decorations",
            "Gifts and Mementos",
            "Invitations and Paper",
            "Jewellery",
            "Shoes"
        ]
    },
    "Amazon_USA":{
        "Accesories":[
            "Boys Fashion",
            "Girls Fashion",
            "Womens Fashion",
            "Mens Fashion"
        ],
        "Accessories":[
            "Boys Fashion",
            "Girls Fashion",
            "Womens Fashion",
            "Mens Fashion"
        ],
        "Arts and Crafts":[
            "Beading and Jewelry Making",
            "Crafting",
            "Fabric",
            "Fabric Decorating",
            "Gift Wrapping Supplies",
            "Knitting and Crochet",
            "Needlework",
            "Organization  Storage and Transport",
            "Painting  Drawing and Art Supplies",
            "Party Decorations and Supplies",
            "Printmaking",
            "Scrapbooking and Stamping",
            "Sewing"
        ],
        "Automotive":[
            "Automotive Enthusiast Merchandise",
            "Car Care",
            "Car Electronics and Accessories",
            "Exterior Accessories",
            "Heavy Duty and Commercial Vehicle Equipment",
            "Interior Accessories",
            "Lights and Lighting Accessories",
            "Motorcycle and Powersports",
            "Oils and Fluids",
            "Paint and Paint Supplies",
            "Performance Parts and Accessories",
            "Replacement Parts",
            "RV Parts and Accessories",
            "Tires and Wheels",
            "Tools and Equipment"
        ],
        "Baby":[
            "Activity and Entertainment",
            "Apparel and Accessories",
            "Baby and Toddler Toys",
            "Baby Care",
            "Baby Stationery",
            "Car Seats and Accessories",
            "Diapering",
            "Feeding",
            "Gifts",
            "Nursery",
            "Potty Training",
            "Pregnancy and Maternity",
            "Safety",
            "Strollers and Accessories",
            "Travel Gear"
        ],
        "Beauty and Personal Care":[
            "Foot  Hand and Nail Care",
            "Fragrance",
            "Hair Care",
            "Makeup",
            "Oral Care",
            "Personal Care",
            "Shave and Hair Removal",
            "Skin Care",
            "Tools and Accessories"
        ],
        "Clothing":[
            "Boys Fashion",
            "Girls Fashion",
            "Mens Fashion",
            "Womens Fashion"
        ],
        "Computers":[
            "Computer Accessories and Peripherals",
            "Computer Components",
            "Computers and Tablets",
            "Data Storage",
            "Laptop Accessories",
            "Monitors",
            "Networking Products",
            "Power Strips and Surge Protectors",
            "Printers",
            "Scanners",
            "Servers",
            "Tablet Accessories",
            "Tablet Replacement Parts",
            "Warranties and Services"
        ],
        "Electronics":[
            "Accessories and Supplies",
            "Camera and Photo",
            "Car and Vehicle Electronics",
            "Cell Phones and Accessories",
            "Computers and Accessories",
            "eBook Readers and Accessories",
            "GPS  Finders and Accessories",
            "Headphones",
            "Home Audio",
            "Office Electronics",
            "Portable Audio and Video",
            "Security and Surveillance",
            "Service Plans",
            "Television and Video",
            "Video Game Consoles and Accessories",
            "Video Projectors",
            "Wearable Technology"
        ],
        "Handbags":[
            "Womens Fashion"
        ],
        "Health and Household":[
            "Baby and Child Care",
            "Health Care",
            "Household Supplies",
            "Medical Supplies and Equipment",
            "Oral Care",
            "Personal Care",
            "Sexual Wellness",
            "Sports Nutrition",
            "Stationery and Gift Wrapping Supplies",
            "Vision Care",
            "Vitamins and Dietary Supplements",
            "Wellness and Relaxation"
        ],
        "Home and Kitchen":[
            "Bath",
            "Bedding",
            "Cleaning Supplies",
            "Event and Party Supplies",
            "Furniture",
            "Heating  Cooling and Air Quality",
            "Home D\u00e9cor",
            "Irons and Steamers",
            "Kids Home Store",
            "Kitchen and Dining",
            "Lighting and Ceiling Fans",
            "Seasonal D\u00e9cor",
            "Storage and Organization",
            "Vacuums and Floor Care",
            "Wall Art"
        ],
        "Industrial and Scientific":[
            "Abrasive and Finishing Products",
            "Additive Manufacturing Products",
            "Adhesives  Sealants and Lubricants",
            "Agricultural Irrigation Equipment",
            "Commercial Door Products",
            "Commercial Lighting",
            "Cutting Tools",
            "Digital Signage",
            "Fasteners",
            "Filtration",
            "Food Service Equipment and Supplies",
            "Hydraulics  Pneumatics and Plumbing",
            "Industrial Electrical",
            "Industrial Hardware",
            "Janitorial and Sanitation Supplies",
            "Lab and Scientific Products",
            "Material Handling Products",
            "Occupational Health and Safety Products",
            "Packaging and Shipping Supplies",
            "Power and Hand Tools",
            "Power Transmission Products",
            "Professional Dental Supplies",
            "Professional Medical Supplies",
            "Raw Materials",
            "Retail Store Fixtures and Equipment",
            "Robotics",
            "Science Education",
            "Test  Measure and Inspect"
        ],
        "Jewelry":[
            "Boys Fashion",
            "Girls Fashion",
            "Womens Fashion"
        ],
        "Luggage":[
            "Backpacks",
            "Carry Ons",
            "Duffels",
            "Garment Bags",
            "Laptop Bags",
            "Luggage Sets",
            "Messenger Bags",
            "Suitcases",
            "Travel Accessories",
            "Travel Totes",
            "Umbrellas"
        ],
        "Pet Supplies":[
            "Birds",
            "Cats",
            "Dogs",
            "Fish and Aquatic Pets",
            "Horses",
            "Reptiles and Amphibians",
            "Small Animals"
        ],
        "School Uniforms":[
            "Girls Fashion"
        ],
        "Shoes":[
            "Boys Fashion",
            "Girls Fashion",
            "Mens Fashion",
            "Womens Fashion"
        ],
        "Software":[
            "Accounting and Finance",
            "Antivirus and Security",
            "Business and Office",
            "Childrens",
            "Education and Reference",
            "Lifestyle and Hobbies",
            "Music",
            "Networking and Servers",
            "Photography and Graphic Design",
            "Programming and Web Development",
            "Tax Preparation",
            "Utilities",
            "Video"
        ],
        "Sports and Outdoors":[
            "Fan Shop",
            "Outdoor Recreation",
            "Sports and Fitness"
        ],
        "Tools and Home Improvement":[
            "Appliances",
            "Building Supplies",
            "Electrical",
            "Hardware",
            "Kitchen and Bath Fixtures",
            "Light Bulbs",
            "Lighting and Ceiling Fans",
            "Measuring and Layout Tools",
            "Paint  Wall Treatments and Supplies",
            "Power and Hand Tools",
            "Rough Plumbing",
            "Safety and Security",
            "Storage and Home Organization",
            "Welding and Soldering"
        ],
        "Toys and Games":[
            "Arts and Crafts",
            "Baby and Toddler Toys",
            "Building Toys",
            "Collectible Toys",
            "Dolls and Accessories",
            "Dress Up and Pretend Play",
            "Games and Accessories",
            "Hobbies",
            "Kids Electronics",
            "Kids Furniture  D\u00e9cor and Storage",
            "Learning and Education",
            "Novelty and Gag Toys",
            "Party Supplies",
            "Play Vehicles",
            "Puppets and Puppet Theaters",
            "Puzzles",
            "Sports and Outdoor Play",
            "Stuffed Animals and Plush Toys",
            "Toy Figures and Playsets",
            "Tricycles  Scooters and Wagons"
        ],
        "Video Games":[
            "Legacy Systems",
            "Mac",
            "Microconsoles",
            "Nintendo 3DS and 2DS",
            "Nintendo DS",
            "Nintendo Switch",
            "PC",
            "PlayStation 3",
            "PlayStation 4",
            "PlayStation Vita",
            "Sony PSP",
            "Wii",
            "Xbox 360",
            "Xbox One"
        ],
        "Watches":[
            "Boys Fashion",
            "Girls Fashion",
            "Mens Fashion",
            "Womens Fashion"
        ]
    },
    "eBay":{
        "Books  Movies and Music":[
            "Books",
            "DVDs and Movies",
            "Music",
            "Musical Instruments and Gear"
        ],
        "Business and Industrial":[
            "Building Materials and Supplies",
            "Fasteners and Hardware",
            "Hydraulics  Pneumatics  Pumps and Plumbing",
            "Industrial Automation and Motion Controls",
            "Light Equipment and Tools",
            "Material Handling",
            "Test  Measurement and Inspection"
        ],
        "Collectibles and Art":[
            "Antiques",
            "Art",
            "Art and Craft Supplies",
            "Coins and Paper Money",
            "Collectibles",
            "Dolls and Teddy Bears",
            "Entertainment Memorabilia",
            "Pottery and Glass",
            "Sports Memorabilia  Fan Shop and Sports Cards",
            "Stamps"
        ],
        "Electronics":[
            "Cameras and Photo",
            "Cell Phones  Smart Watches and Accessories",
            "Computers  Tablets and Network Hardware",
            "Multipurpose Batteries and Power",
            "Portable Audio and Headphones",
            "Radio Communication",
            "Surveillance and Smart Home Electronics",
            "Vehicle Electronics and GPS",
            "Video Games and Consoles",
            "Vintage Electronics",
            "Virtual Reality"
        ],
        "Fashion":[
            "Baby",
            "Costume  Occasion and Specialized Clothing  Shoes and Accessories",
            "Jewelry",
            "Mens Accessories",
            "Shoes",
            "Womens Accessories"
        ],
        "Health and Beauty":[
            "Bath and Body",
            "Hair Care and Styling",
            "Health Care",
            "Makeup",
            "Massage",
            "Medical and Mobility",
            "Nail Care  Manicure and Pedicure",
            "Natural and Alternative Remedies",
            "Oral Care",
            "Shaving and Hair Removal",
            "Skin Care",
            "Tattoos and Body Art",
            "Vision Care"
        ],
        "Home and Garden":[
            "Bath",
            "Food and Beverages",
            "Greeting Cards and Party Supply",
            "Holiday and Seasonal D\u00e9cor",
            "Lamps  Lighting and Ceiling Fans",
            "Rugs and Carpets",
            "Wedding Supplies",
            "Window Treatments and Hardware"
        ],
        "Sporting Goods":[
            "Fishing",
            "Fitness  Running and Yoga",
            "Golf",
            "Hunting",
            "Indoor Games",
            "Tennis and Racquet Sports",
            "Water Sports",
            "Winter Sports"
        ],
        "Toys and Hobbies":[
            "Action Figures",
            "Building Toys",
            "Collectible Card Games",
            "Diecast and Toy Vehicles",
            "Games",
            "Model Railroads and Trains",
            "Models and Kits",
            "Outdoor Toys and Structures",
            "Preschool Toys and Pretend Play",
            "Radio Control and Control Line",
            "Slot Cars",
            "Vintage and Antique Toys"
        ]
    },
    "Flipkart":{
        "Audio and Video":[
            "Audio Accessories",
            "Audio Players and Recorders",
            "Headphones",
            "Home Theaters",
            "Professional Audio Systems",
            "Speakers",
            "Video Accessories",
            "Video Players and Recorders"
        ],
        "Automation and Robotics":[
            "multipurpose controller",
            "Sensors and Alarms",
            "Smart Assistants",
            "Smart Door Locks",
            "Smart Lighting",
            "Smart Monitoring Systems",
            "Smart Pens",
            "Smart Switches",
            "Surveillance Devices"
        ],
        "Automotive":[
            "Automotive Combos",
            "Car Air Purifiers and Air Fresheners",
            "Car and Bike Accessories",
            "Car Dashboard Accessories",
            "Helmets and Riding Gear",
            "Oils and Lubricants",
            "Spares  Tools and Maintenance Service Parts",
            "Tyre and Wheel",
            "Vehicle Body Covers",
            "Vehicle Cleaners",
            "Vehicle Door  Windshield  Windows and Mirrors",
            "Vehicle Lights",
            "Vehicle Mats",
            "Vehicle Repair",
            "Vehicle Safety  Security and Guards",
            "Vehicle Seat and Accessories",
            "Vehicle Stereo and Music System",
            "Vehicle Storage and Organizers",
            "Vehicle Styling",
            "Vehicle Utility Accessories"
        ],
        "Automotive Accesories":[
            "Automotive Combos",
            "Car Air Purifiers and Air Fresheners",
            "Car Dashboard Accessories",
            "Helmets and Riding Gear",
            "Oils and Lubricants",
            "Spares  Tools and Maintenance Service Parts",
            "Tyre and Wheel",
            "Vehicle Body Covers",
            "Vehicle Cleaners",
            "Vehicle Door  Windshield  Windows and Mirrors",
            "Vehicle Lights",
            "Vehicle Mats",
            "Vehicle Repair",
            "Vehicle Safety  Security and Guards",
            "Vehicle Seat and Accessories",
            "Vehicle Stereo and Music System",
            "Vehicle Storage and Organizers",
            "Vehicle Styling",
            "Vehicle Utility Accessories"
        ],
        "Baby Care":[
            "Baby Bath  Hair and Skin Care",
            "Baby Bathing Accessories",
            "Baby Bedding",
            "Baby Cleaners and Detergents",
            "Baby Feeding Bottle and Accessories",
            "Baby Feeding Utensils and Accessories",
            "Baby Food",
            "Baby Gear",
            "Baby Gift Sets and Combo",
            "Baby Grooming",
            "Baby Medical and Health Care",
            "Baby Oral Care",
            "Baby Proofing and Safety",
            "Diaper and Potty Training",
            "Infant Wear",
            "Maternity Care",
            "Nursing and Breast Feeding"
        ],
        "Bags  Wallets and Belts":[
            "Accessories Combo",
            "Bags and Backpacks",
            "Bags  Belts and Wallets Combo",
            "Belts",
            "Belts and Buckles",
            "Garment Covers",
            "Handbags and Clutches",
            "Key Chains",
            "Luggage and Travel",
            "Suspenders",
            "Wallets and Clutches"
        ],
        "Beauty And Grooming":[
            "Bath and Shower",
            "Body and Face Skin Care",
            "Fragrances",
            "Hair Care and Accessory",
            "Health Care Combo",
            "Health Supplements",
            "Home Medical Supplies",
            "Home Medicines",
            "Makeup",
            "Oral Care",
            "Professional medical supplies",
            "Sexual Wellness",
            "Shaving and Beard Care",
            "Womens Personal Hygiene",
            "Womens Safety"
        ],
        "Books":[
            "Arts  Language and Linguistic Books",
            "Biographies  Memoirs and General Non Ficton Books",
            "Children and Young Adult Books",
            "Economics  Business and Management Books",
            "Fiction Books",
            "Graphic Novels and Comics",
            "Healthy Living and Wellness Books",
            "Higher Education and Professional Books",
            "History and Archaeology Books",
            "Lifestyle  Hobby and Sport Books",
            "Literature Books",
            "Other Books",
            "Philosophy and Religion Books",
            "Reference Books",
            "School Books",
            "Self Help Books",
            "Social Science Books",
            "Test Preparation Books"
        ],
        "Building Materials And Supplies":[
            "Bathroom and Kitchen Fittings",
            "Building Raw Materials",
            "Building Supplies Add Ons",
            "Construction Tools and Equipments",
            "Door and Window Fittings",
            "Electrical Hardware",
            "Furniture Parts",
            "Paint Supplies and Equipment",
            "Plumbing Supplies",
            "Solar and Alternate Energy",
            "Wooden Supplies"
        ],
        "Cameras Accessories":[
            "Camera Accessories",
            "Cameras"
        ],
        "Clothing":[
            "Kids Clothing",
            "Mens Clothing",
            "Womens Clothing"
        ],
        "Computers":[
            "Audio Players",
            "Computer Components",
            "Computer Peripherals",
            "Data cards",
            "Desktop PCs",
            "E readers",
            "Laptop Accessories",
            "Laptops",
            "Monitors",
            "Network Components",
            "Printers and Inks",
            "Routers",
            "Software",
            "Storage",
            "Supplies",
            "Tablet Accessories",
            "TV and Video Accessories",
            "Video Players"
        ],
        "Exercise and Fitness":[
            "Fitness Accessories",
            "Fitness Equipment",
            "Mobility Aids and Equipments",
            "Pilates",
            "Yoga"
        ],
        "Eyewear":[
            "Frames",
            "Reading Glasses"
        ],
        "Festive Decor and Gifting":[
            "Festive Decor",
            "Festive Gifts",
            "Fireworks and Crackers",
            "Spiritual Items"
        ],
        "Food and Nutrition":[
            "Artificial Sweetener",
            "Bakery and Baking Essentials",
            "Baking Ingredients and Essential Products",
            "Beverages",
            "Biscuit  Cookie and Rusk",
            "Breakfast Cereal",
            "Breakfast Mixes and Cereals",
            "Butter",
            "Buttermilk",
            "Cake and Pastry Mix",
            "Canned Food",
            "Cereal Bars",
            "Cheese",
            "Chips",
            "Chocolates",
            "Chutneys",
            "Coffee Powder",
            "Condensed Milk",
            "Confectioneries and Sweets",
            "Confectionery Products",
            "Dairy Cream",
            "Dairy Products",
            "Drinking Water",
            "Dry Fruit  Nut and Seed",
            "Edible Oil",
            "Edible Oils and Ghee",
            "Egg",
            "Energy Drink Products",
            "Flour and Sooji",
            "Food and Nutrition Combo",
            "Food Combo",
            "Food Spreads",
            "Fruit Crush",
            "Fruit Juice",
            "Fruits",
            "Fruits and Vegetables",
            "Fruit Squash",
            "Fryum",
            "Ghee and Vanaspati",
            "Grain",
            "Health and Nutrition",
            "Herb and Seasoning",
            "Honey",
            "Instant Drink Mix",
            "Jaggery",
            "Jams and Marmalade",
            "Jams  Spreads and Honey",
            "Lassi",
            "Meat",
            "Milk",
            "Milk Powder",
            "Murabba and Gulkand",
            "Namkeen",
            "Noodle",
            "Noodles and Pasta",
            "Nuts  Dry Fruits and Combos",
            "Paneer and Tofu",
            "Papad",
            "Pasta",
            "Paste and Puree",
            "Pickle",
            "Popcorn",
            "Poultry  Meat and Seafood",
            "Powdered Drink Mix",
            "Pulses",
            "Ready Meal and Mixes",
            "Ready to Cook and Eat",
            "Rice",
            "Salt",
            "Sauce and Dip",
            "Seafood",
            "Snacks and Nibbles",
            "Soft Drink Products",
            "Soup and Dry Soup Mix",
            "Spice Powder and Masala",
            "Spices  Condiments and Sauces",
            "Staples",
            "Sugar",
            "Sweets and Mixes",
            "Syrup",
            "Tea Powder",
            "Vegetables",
            "Vermicelli",
            "Vinegar",
            "Yogurt and Curd Products"
        ],
        "Footwear":[
            "Kids and Infant Footwear",
            "Mens Footwear",
            "Womens Footwear"
        ],
        "Furniture":[
            "Cabinets",
            "Chairs",
            "Dining Tables and Sets",
            "Drawers",
            "Furniture Accessories",
            "Mattresses",
            "Shelves",
            "Showcases",
            "Sofas",
            "Stands",
            "Tables",
            "TV Units and Cabinets"
        ],
        "Gaming":[
            "Games",
            "Gaming Accessories",
            "Gaming Components",
            "Gaming Consoles",
            "Gaming Laptops",
            "Membership Cards"
        ],
        "Health and Personal Care Appliances":[
            "Health Care",
            "Personal Care Appliances"
        ],
        "Health Care":[
            "Health Care Combo",
            "Health Supplements",
            "Home Medical Supplies",
            "Home Medicines",
            "Professional medical supplies",
            "Womens Safety"
        ],
        "Home and Kitchen":[
            "Home Appliances",
            "Kitchen Appliances"
        ],
        "Home Cleaning and Bathroom Accessories":[
            "Bathroom Accessories",
            "Cleaning Supplies",
            "HouseHold Supplies"
        ],
        "Home Decor":[
            "Clocks",
            "Diyas  Candles and Holders",
            "Flowers and Vases",
            "Home Fragrance",
            "Hookah and Hookah Accessories",
            "Paintings and Posters",
            "Photo Frames and Albums",
            "Showpieces and Decor Accents",
            "Stickers and Wallpapers",
            "Wall Decor Items",
            "Windchimes and Dream catchers"
        ],
        "Home Entertainment":[
            "Audio Players",
            "DTH",
            "Home Audio",
            "MP3 playersorIpods Accessories",
            "Televisions",
            "Video Players and Accessories"
        ],
        "Home Furnishing":[
            "Bath Linen",
            "Bed Linen and Blankets",
            "Covers and Protectors",
            "Curtains and Accessories",
            "Cushions and Pillows",
            "Floor Coverings",
            "Kitchen and Table Linen",
            "Sofa and Curtain Fabrics"
        ],
        "Home Improvement":[
            "Home Safety",
            "Home Utilities and Organizers",
            "Lawn and Gardening",
            "Tools and Measuring Equipment"
        ],
        "Home Lighting":[
            "Decor lighting and Accessories",
            "Utility Lighting"
        ],
        "Industrial and Scientific Supplies":[
            "Additive Manufacturing Products",
            "Industrial Measurement Devices",
            "Industrial Testing Devices",
            "Lab and Scientific Products",
            "Packaging and Shipping Products",
            "Safety Products"
        ],
        "Jewellery":[
            "Artificial Jewellery",
            "Gemstones  Coins and Bars",
            "Precious Articles",
            "Precious Jewellery",
            "Silver Jewellery"
        ],
        "Kids Accessories":[
            "School Supplies"
        ],
        "Kitchen  Cookware and Serveware":[
            "Bakeware",
            "Barware",
            "Cookware",
            "Disposable Supplies",
            "Gas Stove and Accessories",
            "Hand Juicers and Grinders",
            "Kitchen Storage and Containers",
            "Kitchen Tools",
            "Knives  Choppers and Cutters",
            "Lunch Boxes  Bottles and Flasks",
            "Outdoor Cooking",
            "Spray Bottle",
            "Tableware and Dinnerware"
        ],
        "Mobiles and Accessories":[
            "Mobile Accessories",
            "Mobiles",
            "Tablet Accessories",
            "Tablets"
        ],
        "Music":[
            "Audio CD"
        ],
        "Musical Instruments":[
            "Accessories",
            "Drums and Percussion",
            "Electronic Instruments",
            "Keys and Synthesizers",
            "String Instruments",
            "StudioorStage Equipment and Accessories",
            "Wind Instruments"
        ],
        "Music  Movies and Posters":[
            "Movies and TV Show"
        ],
        "Pens and Stationery":[
            "Art Supplies",
            "Calculators",
            "College Supplies",
            "Diaries and Notebooks",
            "Lab Equipment",
            "Office Electronics",
            "Office Equipments",
            "Office Supplies",
            "Pens",
            "Tailoring and Embroidery Supplies"
        ],
        "Pet Supplies":[
            "Birds",
            "Cats",
            "Dogs",
            "Fish and Aquatic",
            "Grooming and Hygiene",
            "Health and Safety",
            "Horse",
            "Large Animals",
            "Small Animals"
        ],
        "Sports":[
            "Air hockey",
            "Archery",
            "Athletics",
            "Badminton",
            "Baseball",
            "Basketball",
            "Boating",
            "Boomerang",
            "Bowling",
            "Boxing",
            "Camping and Hiking",
            "Carrom",
            "Chess",
            "Climbing",
            "Cricket",
            "Cycling",
            "Discus Throw",
            "Diving",
            "Fishing",
            "Foosball",
            "Football",
            "Frisbees",
            "Golf",
            "Handball",
            "Hobby Hunting",
            "Hockey",
            "Horse Riding",
            "Jumping Trainers",
            "Kite Flying",
            "Laccrose",
            "Netball",
            "Other Ball Sports",
            "Pickleball",
            "Rugby",
            "Running",
            "Scuba Diving",
            "Shooting",
            "Skating",
            "Slacklining",
            "Sport Accessories",
            "Squash",
            "Surfing",
            "Swimming",
            "Table Tennis",
            "Taekwondo",
            "Tennis",
            "Throwball",
            "Volleyball",
            "Water Polo"
        ],
        "Sunglasses":[
            
        ],
        "Toys":[
            "Action Figures",
            "Art and Craft Toys",
            "Baby Toys",
            "Blocks and Building Sets",
            "Board Games",
            "Card Games",
            "Dolls and Doll Houses",
            "Educational Toys",
            "Gag Toys",
            "Hobby Kits",
            "Learning and Educational Toys",
            "Magic Kits",
            "Magic Springs",
            "Marbles",
            "Mikado Sticks",
            "Musical Instruments and Toys",
            "Outdoor Toys",
            "Party Supplies",
            "Pogo Sticks",
            "Puppets",
            "Puzzles",
            "Puzzles and Board Games",
            "Remote Control Toys",
            "Ride Ons",
            "Role Play Toys",
            "Slime and Putty Toys",
            "Soft Toys",
            "Spinning and Press n Launch Toys",
            "Sports",
            "Toy Cars  Trains and Bikes",
            "Toy Guns and Others",
            "Toy Sport",
            "Tricycles",
            "Wind Spinner Toys",
            "Yoyo"
        ],
        "Watches":[
            "Watch Accessories",
            "Wrist Watches"
        ],
        "Wearable Smart Devices":[
            "Bluetooth Hats",
            "Bluetooth Item Finders",
            "Smart Bands",
            "Smart Glasses",
            "Smart Headphones",
            "Smart Trackers",
            "Smart Watches",
            "Wearable Accessories"
        ]
    },
    "Bonanza":{
        "Antiques":[
            "Antiquities",
            "Architectural and Garden",
            "Asian Antiques",
            "Decorative Arts",
            "Ethnographic",
            "Furniture",
            "Home and Hearth",
            "Linens and Textiles (Pre 1930)",
            "Maps  Atlases and Globes",
            "Maritime",
            "Mercantile  Trades and Factories",
            "Musical Instruments (Pre 1930)",
            "Other",
            "Periods and Styles",
            "Primitives",
            "Reproduction Antiques",
            "Restoration and Care",
            "Rugs and Carpets",
            "Science and Medicine (Pre 1930)",
            "Sewing (Pre 1930)",
            "Silver"
        ],
        "Art":[
            "Art Drawings",
            "Art Prints",
            "Art Sculptures",
            "Folk Art and Indigenous Art",
            "Mixed Media Art and Collage Art",
            "Other Art",
            "Paintings",
            "Textile Art and Fiber Art"
        ],
        "Baby":[
            "Baby Gear",
            "Baby Safety and Health",
            "Bathing and Grooming",
            "Car Safety Seats",
            "Diapering",
            "Feeding",
            "Keepsakes and Baby Announcements",
            "Nursery Bedding",
            "Nursery D\u00e9cor",
            "Nursery Furniture",
            "Other",
            "Potty Training",
            "Strollers and Accessories",
            "Toys for Baby",
            "Wholesale Lots"
        ],
        "Books":[
            "Accessories",
            "Antiquarian and Collectible",
            "Audiobooks",
            "Catalogs",
            "Children and Young Adults",
            "Magazine Back Issues",
            "Nonfiction",
            "Other Books",
            "Textbooks  Education and Reference",
            "Wholesale and Bulk Lots"
        ],
        "Business and Industrial":[
            "Adhesives  Sealants and Tapes",
            "Agriculture and Forestry",
            "Building Materials and Supplies",
            "Cleaning and Janitorial Supplies",
            "CNC  Metalworking and Manufacturing",
            "Construction",
            "Electrical Equipment and Supplies",
            "Facility Maintenance and Safety",
            "Fasteners and Hardware",
            "Fuel and Energy",
            "Healthcare  Lab and Dental",
            "Heavy Equipment  Parts and Attachments",
            "HVAC and Refrigeration",
            "Hydraulics  Pneumatics  Pumps and Plumbing",
            "Industrial Automation and Motion Controls",
            "Light Equipment and Tools",
            "Material Handling",
            "Office",
            "Other Business and Industrial",
            "Printing and Graphic Arts",
            "Restaurant and Food Service",
            "Retail and Services",
            "Test  Measurement and Inspection",
            "Websites and Businesses for Sale"
        ],
        "Cameras and Photo":[
            "Binoculars and Telescopes",
            "Camcorders",
            "Camera and Photo Accessories",
            "Camera Drone Parts and Accs",
            "Camera Drones",
            "Digital Cameras",
            "Digital Photo Frames",
            "Film Photography",
            "Flashes and Flash Accessories",
            "Lenses and Filters",
            "Lighting and Studio",
            "Manuals and Guides",
            "Other",
            "Replacement Parts and Tools",
            "Tripods and Supports",
            "Video Production and Editing",
            "Vintage Movie and Photography"
        ],
        "Cell Phones and Accessories":[
            "Cell Phone Accessories",
            "Cell Phones and Smartphones",
            "Mixed Lots",
            "PDAs",
            "Smart Watch Accessories",
            "Vintage Cell Phones"
        ],
        "Coins and Paper Money":[
            "Bullion",
            "Coins: Ancient",
            "Coins: Canada",
            "Coins: Medieval",
            "Coins: US",
            "Coins: World",
            "Exonumia",
            "Other",
            "Paper Money: US",
            "Paper Money: World",
            "Publications and Supplies",
            "Stocks and Bonds  Scripophily"
        ],
        "Collectibles":[
            "Advertising",
            "Animals",
            "Animation Art and Characters",
            "Arcade  Jukeboxes and Pinball",
            "Autographs",
            "Banks  Registers and Vending",
            "Barware",
            "Beads",
            "Bottles and Insulators",
            "Breweriana  Beer",
            "Casino",
            "Clocks",
            "Comics",
            "Credit  Charge Cards",
            "Cultures and Ethnicities",
            "Decorative Collectibles",
            "Disneyana",
            "Fantasy  Mythical and Magic",
            "Historical Memorabilia",
            "Holiday and Seasonal",
            "Kitchen and Home",
            "Knives  Swords and Blades",
            "Lamps  Lighting",
            "Linens and Textiles (1930 Now)",
            "Metalware",
            "Militaria",
            "Non Sport Trading Cards",
            "Paper",
            "Pens and Writing Instruments",
            "Pez  Keychains  Promo Glasses",
            "Photographic Images",
            "Pinbacks  Bobbles  Lunchboxes",
            "Postcards",
            "Radio  Phonograph  TV  Phone",
            "Religion and Spirituality",
            "Rocks  Fossils and Minerals",
            "Science and Medicine (1930 Now)",
            "Science Fiction and Horror",
            "Sewing (1930 Now)",
            "Souvenirs and Travel Memorabilia",
            "Tobacciana",
            "Tools  Hardware and Locks",
            "Transportation",
            "Vanity  Perfume and Shaving",
            "Vintage  Retro  Mid Century",
            "Wholesale Lots"
        ],
        "ComputersorTablets and Networking":[
            "3D Printers and Supplies",
            "Computer Cables and Connectors",
            "Computer Components and Parts",
            "Desktops and All In Ones",
            "Drives  Storage and Blank Media",
            "Enterprise Networking  Servers",
            "Home Networking and Connectivity",
            "iPadorTabletoreBook Accessories",
            "iPads  Tablets and eBook Readers",
            "Keyboards  Mice and Pointing",
            "Laptop and Desktop Accessories",
            "Laptops and Netbooks",
            "Manuals and Resources",
            "Mixed Lots",
            "Monitors  Projectors and Accs",
            "Other",
            "Power Protection  Distribution",
            "Printers  Scanners and Supplies",
            "Software",
            "Tablet and eBook Reader Parts",
            "Vintage Computing"
        ],
        "Consumer Electronics":[
            "Home Telephones and Accessories",
            "Mixed Lots",
            "Multipurpose Batteries and Power",
            "Portable Audio and Headphones",
            "Radio Communication",
            "Surveillance and Smart Home Electronics",
            "TV  Video and Home Audio",
            "Vehicle Electronics and GPS",
            "Vintage Electronics",
            "Virtual Reality",
            "Voice Enabled Smart Assistants"
        ],
        "Crafts":[
            "Art Supplies",
            "Beads and Jewelry Making",
            "Fabric Painting and Decorating",
            "Glass and Mosaics",
            "Handcrafted and Finished Pieces",
            "Home Arts and Crafts",
            "Kids Crafts",
            "Leathercrafts",
            "Multi Purpose Craft Supplies",
            "Needlecrafts and Yarn",
            "Other Crafts",
            "Scrapbooking and Paper Crafts",
            "Sculpting  Molding and Ceramics",
            "Stamping and Embossing",
            "Wholesale Lots"
        ],
        "Digital Goods":[
            "Computer Software and Games",
            "Digital Art",
            "Movies",
            "Music",
            "Photography"
        ],
        "Dolls and Bears":[
            "Bears",
            "Dollhouse Miniatures",
            "Dolls",
            "Paper Dolls",
            "Wholesale Lots"
        ],
        "DVDs and Movies":[
            "DVD  HD DVD and Blu ray",
            "Film",
            "Laserdisc",
            "Other Formats",
            "Storage and Media Accessories",
            "UMD",
            "VHS Tapes",
            "Wholesale Lots"
        ],
        "Entertainment Memorabilia":[
            "Autographs Original",
            "Autographs Reprints",
            "Movie Memorabilia",
            "Music Memorabilia",
            "Other",
            "Television Memorabilia",
            "Theater Memorabilia",
            "Video Game Memorabilia"
        ],
        "Everything Else":[
            "Career Development and Education",
            "Funeral and Cemetery",
            "Genealogy",
            "Information Products",
            "LP Parent",
            "Metaphysical",
            "Other",
            "Personal Development",
            "Personal Security",
            "Religious Products and Supplies",
            "Reward Points and Incentives",
            "Weird Stuff"
        ],
        "Fashion":[
            "Baby",
            "Costumes  Reenactment  Theater",
            "Dancewear",
            "Kids",
            "Men",
            "Specialty",
            "Uniforms and Work Clothing",
            "Wedding and Formal Occasion",
            "Women",
            "Womens Shoes"
        ],
        "Health and Beauty":[
            "Bath and Body",
            "E Cigarettes  Vapes and Accs",
            "Fragrances",
            "Hair Care and Styling",
            "Health Care",
            "Makeup",
            "Massage",
            "Medical and Mobility",
            "Nail Care  Manicure and Pedicure",
            "Natural and Alternative Remedies",
            "Oral Care",
            "Other",
            "Salon and Spa Equipment",
            "Shaving and Hair Removal",
            "Skin Care",
            "Sun Protection and Tanning",
            "Tattoos and Body Art",
            "Vision Care",
            "Vitamins and Dietary Supplements",
            "Wholesale Lots"
        ],
        "Home and Garden":[
            "Bath",
            "Bedding",
            "Food and Beverages",
            "Fresh Cut Flowers and Supplies",
            "Furniture",
            "Greeting Cards and Party Supply",
            "Holiday and Seasonal D\u00e9cor",
            "Home D\u00e9cor",
            "Home Improvement",
            "Household Supplies and Cleaning",
            "Kids and Teens at Home",
            "Kitchen  Dining and Bar",
            "Lamps  Lighting and Ceiling Fans",
            "Major Appliances",
            "Other Home and Garden",
            "Rugs and Carpets",
            "Tools and Workshop Equipment",
            "Wedding Supplies",
            "Wholesale Lots",
            "Window Treatments and Hardware",
            "Yard  Garden and Outdoor Living"
        ],
        "Jewelry and Watches":[
            "Childrens Jewelry",
            "Engagement and Wedding",
            "Ethnic  Regional and Tribal",
            "Fashion Jewelry",
            "Fine Jewelry",
            "Handcrafted  Artisan Jewelry",
            "Jewelry Boxes and Organizers",
            "Jewelry Design and Repair",
            "Loose Beads",
            "Loose Diamonds and Gemstones",
            "Mens Jewelry",
            "Other",
            "Vintage and Antique Jewelry",
            "Watches",
            "Wholesale Lots"
        ],
        "Music":[
            "Accessories",
            "Cassettes",
            "CDs",
            "Other Formats",
            "Records",
            "Wholesale Lots"
        ],
        "Musical Instruments and Gear":[
            "Brass",
            "DJ Equipment",
            "Equipment",
            "Guitars and Basses",
            "Instruction Books  CDs and Video",
            "Karaoke Entertainment",
            "Other",
            "Percussion",
            "Pianos  Keyboards and Organs",
            "Pro Audio Equipment",
            "Sheet Music and Song Books",
            "Stage Lighting and Effects",
            "String",
            "Vintage Musical Instruments",
            "Wind and Woodwind"
        ],
        "Parts and Accessories":[
            "Apparel and Merchandise",
            "ATV Parts",
            "Aviation Parts and Accessories",
            "Boat Parts",
            "Car and Truck Parts",
            "Commercial Truck Parts",
            "Golf Car Parts and Accessories",
            "In Car Technology  GPS and Security",
            "Manuals and Literature",
            "Motorcycle Accessories",
            "Motorcycle Parts",
            "Other",
            "Other Vehicle Parts",
            "Performance and Racing Parts",
            "Personal Watercraft Parts",
            "RV  Trailer and Camper Parts",
            "Salvage Parts Cars",
            "Scooter Parts",
            "Services and Installation",
            "Snowmobile Parts",
            "Vintage Car and Truck Parts",
            "Wholesale Lots"
        ],
        "Pet Supplies":[
            "Backyard Poultry Supplies",
            "Bird Supplies",
            "Cameras",
            "Cat Supplies",
            "Dog Supplies",
            "Fish and Aquariums",
            "Pet Memorials and Urns",
            "Reptile Supplies",
            "Trackers",
            "Wholesale Lots"
        ],
        "Pottery and Glass":[
            "Glass",
            "Pottery and China"
        ],
        "Specialty Services":[
            "Artistic Services",
            "Custom Clothing and Jewelry",
            "Graphic and Logo Design",
            "Home Improvement Services",
            "Item Based Services",
            "Media Editing and Duplication",
            "Other Services",
            "Printing and Personalization",
            "Restoration and Repair",
            "Web and Computer Services"
        ],
        "Sporting Goods":[
            "Boxing  Martial Arts and MMA",
            "Cycling",
            "Fishing",
            "Fitness  Running and Yoga",
            "Golf",
            "Hunting",
            "Indoor Games",
            "Other",
            "Outdoor Sports",
            "Team Sports",
            "Tennis and Racquet Sports",
            "Water Sports",
            "Wholesale Lots",
            "Winter Sports"
        ],
        "Sports Mem  Cards and Fan Shop":[
            "Autographs Original",
            "Autographs Reprints",
            "Fan Apparel and Souvenirs",
            "Game Used Memorabilia",
            "Sports Stickers  Sets and Albums",
            "Sports Trading Cards",
            "Vintage Sports Memorabilia",
            "Wholesale Lots"
        ],
        "Stamps":[
            "Africa",
            "Asia",
            "Australia and Oceania",
            "British Colonies and Territories",
            "Canada",
            "Caribbean",
            "Europe",
            "Great Britain",
            "Latin America",
            "Middle East",
            "Other",
            "Publications and Supplies",
            "Specialty Philately",
            "Topical Stamps",
            "United States",
            "Worldwide"
        ],
        "Tickets and Experiences":[
            "Other",
            "Sports",
            "Theater",
            "Theme Park and Club Passes"
        ],
        "Toys and Hobbies":[
            "Action Figures",
            "Beanbag Plush  Beanie Babies",
            "Building Toys",
            "Classic Toys",
            "Collectible Card Games",
            "Diecast and Toy Vehicles",
            "Educational",
            "Electronic  Battery and Wind Up",
            "Fast Food and Cereal Premiums",
            "Games",
            "Marbles",
            "Model Railroads and Trains",
            "Models and Kits",
            "Outdoor Toys and Structures",
            "Preschool Toys and Pretend Play",
            "Puzzles",
            "Radio Control and Control Line",
            "Robots  Monsters and Space Toys",
            "Slot Cars",
            "Stuffed Animals",
            "Toy Soldiers",
            "TV and Movie Character Toys",
            "Vintage and Antique Toys",
            "Wholesale Lots"
        ],
        "Travel":[
            "Airline",
            "Campground and RV Parks",
            "Car Rental",
            "Cruises",
            "Lodging",
            "Luggage Accessories",
            "Maps",
            "Other",
            "Rail",
            "Travel Accessories",
            "Vacation Packages",
            "Vintage Luggage and Travel Accs"
        ],
        "Video Games and Consoles":[
            "Manuals  Inserts and Box Art",
            "Merchandise",
            "Mixed Lots",
            "Original Game Cases and Boxes",
            "Prepaid Gaming Cards",
            "Replacement Parts and Tools",
            "Strategy Guides and Cheats",
            "Video Game Accessories",
            "Video Games"
        ]
    },
    "Amazon_India":{
        "Baby":[
            "Activity_and_Play_Time",
            "Baby_Care",
            "Baby_Carriers",
            "Baby_Clothing",
            "Baby_Safety",
            "Baby_Shoes",
            "Bedding__Furniture_and_Room_Décor",
            "Car_Seats_and_Accessories",
            "Diapering_and_Nappy_Changing",
            "Feeding",
            "Gift_Packs",
            "Maternity",
            "Pacifiers_and_Teethers",
            "Potty_Training_and_Step_Stools",
            "Strollers__Buggies_and_Prams"
        ],
        "Bags__Wallets_and_Luggage":[
            "Bags_and_Backpacks",
            "Handbags_and_Clutches",
            "Luggage",
            "Shopping_Bags_and_Baskets",
            "Travel_Accessories",
            "Wallets__Card_Cases_and_Money_Organizers"
        ],
        "Beauty":[
            "Bath_and_Body",
            "Fragrance",
            "Hair_Care_and_Styling",
            "Make_up_and_Nails",
            "Skin_Care",
            "Tools_and_Accessories"
        ],
        "Books":[
            "Action_and_Adventure",
            "Arts__Film_and_Photography",
            "Biographies__Diaries_and_True_Accounts",
            "Business_and_Economics",
            "Childrens_and_Young_Adult",
            "Comics_and_Mangas",
            "Computing__Internet_and_Digital_Media",
            "Crafts__Hobbies_and_Home",
            "Crafts__Home_and_Lifestyle",
            "Crime__Thriller_and_Mystery",
            "Exam Preparation",
            "Exam_Preparation",
            "Fantasy__Horror_and_Science_Fiction",
            "Health__Family_and_Personal_Development",
            "Historical Fiction",
            "Historical_Fiction",
            "History",
            "Humour",
            "Language__Linguistics_and_Writing",
            "Law",
            "Literature_and_Fiction",
            "Maps_and_Atlases",
            "Politics",
            "Reference",
            "Religion",
            "Religion_and_Spirituality",
            "Romance",
            "School Bundles",
            "Sciences__Technology_and_Medicine",
            "Society_and_Social_Sciences",
            "Sports",
            "Textbooks_and_Study_Guides",
            "Travel"
        ],
        "Car_and_Motorbike":[
            "Car_and_Motorbike_Care",
            "Car_and_Vehicle_Electronics",
            "Car_Parts",
            "Car_Tyres_and_Rims",
            "Gifts_and_Merchandise",
            "Motorbike_Accessories_and_Parts",
            "Oils_and_Fluids",
            "Paintwork"
        ],
        "Clothing_and_Accessories":[
            "Baby",
            "Boys",
            "Girls",
            "Men",
            "Women"
        ],
        "Computers_and_Accessories":[
            "Accessories_and_Peripherals",
            "Components",
            "Desktops",
            "External_Devices_and_Data_Storage",
            "Laptops",
            "Monitors",
            "Networking_Devices",
            "Scanners",
            "Tablets",
            "Warranties"
        ],
        "Electronics":[
            "Accessories",
            "Cameras_and_Photography",
            "Car_and_Vehicle_Electronics",
            "Computers_and_Accessories",
            "GPS_and_Accessories",
            "Home_Audio",
            "Home_Theater__TV_and_Video",
            "Mobiles_and_Accessories",
            "Portable_Media_Players",
            "Tablets",
            "Telephones_and_Accessories",
            "Warranties",
            "Wearable Technology"
        ],
        "Grocery_and_Gourmet_Foods":[
            "Canned_and_Jarred_Food",
            "Cereal_and_Muesli",
            "Coffee__Tea_and_Beverages",
            "Cooking_and_Baking_Supplies",
            "Dried_Fruits__Nuts_and_Seeds",
            "Hampers_and_Gourmet_Gifts",
            "Jams__Honey_and_Spreads",
            "Pasta_and_Noodles",
            "Pickles",
            "Ready_To_Eat_and_Cook",
            "Snack_Foods",
            "Sweets__Chocolate_and_Gum"
        ],
        "Health_and_Personal_Care":[
            "Bath_and_Shower",
            "Beauty_Tools_and_Accessories",
            "Diet_and_Nutrition",
            "Hair_Care_and_Styling",
            "Health_Care",
            "Home_Medical_Supplies_and_Equipment",
            "Household_Supplies",
            "Personal_Care",
            "Personal_Care_and_Health_Appliances",
            "Sexual_Wellness_and_Sensuality",
            "Skin_Care"
        ],
        "Home_and_Kitchen":[
            "Artwork",
            "Craft_Materials",
            "Fresh_Flowers",
            "Furniture",
            "Heating__Cooling_and_Air_Quality",
            "Home_and_Décor",
            "Home_Furnishing",
            "Home_Improvement",
            "Home_Storage_and_Organization",
            "Indoor_Lighting",
            "Kitchen_and_Dining",
            "Kitchen_and_Home_Appliances",
            "Large_Appliances"
        ],
        "Industrial_and_Scientific":[
            "Commercial_Door_Products",
            "Cutting_Tools",
            "Fasteners",
            "Filtration",
            "Food_Service_Equipment_and_Supplies",
            "Hydraulics__Pneumatics_and_Plumbing",
            "Industrial_Electrical",
            "Industrial_Hardware",
            "Janitorial_and_Sanitation_Supplies",
            "Lab_and_Scientific_Products",
            "Material_Handling_Products",
            "Occupational_Health_and_Safety_Products",
            "Packaging_and_Shipping_Supplies",
            "Power_and_Hand_Tools",
            "Power_Transmission_Products",
            "Professional_Dental_Supplies",
            "Professional_Medical_Supplies",
            "Robotics",
            "Tapes__Adhesives_and_Sealers",
            "Test__Measure_and_Inspect"
        ],
        "Jewellery":[
            "Baby",
            "Boys",
            "Coins_and_Bars",
            "Girls",
            "Jewellery_Boxes_and_Care",
            "Loose_Gemstones_and_Diamonds",
            "Men",
            "Women"
        ],
        "Movies_and_TV_Shows":[
            "TV_Shows"
        ],
        "Music":[
            "Alternative_and_Indie",
            "Bhangra",
            "Blues",
            "Country",
            "Easy Listening",
            "Film Songs",
            "Ghazals",
            "Gospel",
            "Indian_Classical",
            "Indi Pop",
            "Jazz",
            "Pop",
            "Rabindra Sangeet",
            "Reggae",
            "Rock",
            "Special Interest",
            "Western Classical",
            "World_Music"
        ],
        "Musical Instruments":[
            "Bass Guitars & Gear",
            "DJ & VJ Equipment",
            "Drums & Percussion",
            "Guitars & Gear",
            "Karaoke Equipment",
            "Microphones",
            "PA & Stage",
            "Piano & Keyboard",
            "Recording & Computer",
            "String Instruments",
            "Synthesizer & Sampler",
            "Wind Instruments"
        ],
        "Musical_Instruments":[
            "Bass_Guitars_and_Gear",
            "DJ_and_VJ_Equipment",
            "Drums_and_Percussion",
            "Guitars_and_Gear",
            "Guitars__Basses_and_Gear",
            "Karaoke_Equipment",
            "Microphones",
            "PA_and_Stage",
            "Piano_and_Keyboard",
            "Recording_and_Computer",
            "String_Instruments",
            "Synthesisers__Samplers_and_Digital_Instruments",
            "Wind_Instruments"
        ],
        "Office_Products":[
            "Calculators",
            "Calendars__Planners_and_Personal_Organisers",
            "Envelopes_and_Postal_Supplies",
            "Office_Electronics",
            "Office_Paper_Products",
            "Office_Supplies",
            "Stationery"
        ],
        "Outdoor_Living":[
            "Backyard_Birding_Supplies",
            "Barbecue_and_Outdoor_Dining",
            "Beekeeping_Equipment",
            "Garden_and_Outdoor_Furniture",
            "Gardening",
            "Mowers_and_Outdoor_Power_Tools",
            "Outdoor_Décor",
            "Pest_Control",
            "Plants__Seeds_and_Bulbs",
            "Solar_and_Wind_Power"
        ],
        "Pet_Supplies":[
            "Birds",
            "Cats",
            "Dogs",
            "Fish_and_Aquatics",
            "Small_Animals"
        ],
        "Shoes_and_Handbags":[
            "Handbags__Purses_and_Clutches",
            "Shoe_Care_and_Accessories",
            "Shoes"
        ],
        "Software":[
            "Accounting_and_Finance",
            "Antivirus_and_Security",
            "Business_and_Office",
            "Childrens_Software",
            "Education_and_Reference",
            "Graphics_and_Design",
            "Language_and_Travel",
            "Networking_and_Servers",
            "Operating_Systems",
            "Photography",
            "Programming_and_Web_Development",
            "System_Utility_Software"
        ],
        "Sports__Fitness_and_Outdoors":[
            "Accessories",
            "Archery",
            "Badminton",
            "Baseball",
            "Basketball",
            "Billiards",
            "Boxing",
            "Camping_and_Hiking",
            "Climbing",
            "Cricket",
            "Cycling",
            "Darts_and_Dartboards",
            "Disc_Sports",
            "Equestrian_Sports",
            "Exercise_and_Fitness",
            "Fan_Shop",
            "Field_Hockey",
            "Fishing",
            "Football",
            "Footwear",
            "Golf",
            "Gymnastics",
            "Martial_Arts",
            "Rugby",
            "Running",
            "Skates__Skateboards_and_Scooters",
            "Snooker",
            "Sports_Clothing",
            "Sports_Gadgets",
            "Squash",
            "Table_Tennis",
            "Team_Handball",
            "Tennis",
            "Track_and_Field",
            "Volleyball",
            "Water_Sports"
        ],
        "Toys_and_Games":[
            "Action_and_Toy_Figures",
            "Arts_and_Crafts",
            "Baby_and_Toddler_Toys",
            "Bikes__Trikes_and_Ride_Ons",
            "Building_and_Construction_Toys",
            "Coin_and_Stamp_Collecting",
            "Collectible_Trading_Cards_and_Accessories",
            "Cosmetics_and_Jewellery",
            "Die_Cast_and_Toy_Vehicles",
            "Dolls_and_Accessories",
            "Dressing_Up_and_Costumes",
            "Electronic_Toys",
            "Games",
            "Learning_and_Education",
            "Marble_Runs",
            "Model_Building_Kits",
            "Model_Trains_and_Railway_Sets",
            "Musical_Toy_Instruments",
            "Novelty_and_Gag_Toys",
            "Party_Supplies",
            "Pretend_Play",
            "Puppets_and_Puppet_Theatres",
            "Puzzles",
            "Radio_and_Remote_Control",
            "Real_Food_Appliances",
            "School_Supplies",
            "Sport_and_Outdoor"
        ],
        "Video_Games":[
            "Microconsoles_and_Handhelds",
            "Nintendo_3DS",
            "Nintendo_DS",
            "PC_Games",
            "PlayStation_2",
            "PlayStation_3",
            "PlayStation_4",
            "PlayStation_Vita",
            "PSP",
            "Wii",
            "Wii_U",
            "Xbox_360"
        ],
        "Watches":[
            "Accessories",
            "Boys",
            "Girls",
            "Men",
            "Women"
        ]
    }
}